name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main", "Ronaldo93-patch-1" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Install Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos)"
      - name: Build
        run: |
          make package
